export const PATTERN_UPSELLS: any[] = [
    {
        name: "pattern-feature-comparison",
        title: "Pattern: Products Feature Comparison",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-feature-comparison.png",
    },
    {
        name: "pattern-employee-information-table",
        title: "Pattern: Employee Information Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-employee-information-table.png",
    },
    {
        name: "pattern-problems-solutions-table",
        title: "Pattern: Problems &amp; Solutions Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-problems-solutions-table.png",
    },
    {
        name: "pattern-pros-and-cons-colorful",
        title: "Pattern: Pros and Cons (Colorful)",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pros-and-cons-colorful.png",
    },
    {
        name: "pattern-pros-and-cons-table-simple",
        title: "Pattern: Pros and Cons Table (Simple)",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pros-and-cons-table-simple.png",
    },
    {
        name: "pattern-pros-cons-table-with-featured-product",
        title: "Pattern: Pros &amp; Cons Table with Featured Product",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pros-cons-table-with-featured-product.png",
    },
    {
        name: "pattern-top-products-comparison-table",
        title: "Pattern: Top Products Comparison Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-top-products-comparison-table.png",
    },
    {
        name: "pattern-product-comparison-table-versus",
        title: "Pattern: Product Comparison Table (Versus)",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-product-comparison-table-versus.png",
    },
    {
        name: "pattern-pricing-table-with-features-comparison",
        title: "Pattern: Pricing Table with Features Comparison",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pricing-table-with-features-comparison.png",
    },
    {
        name: "pattern-pricing-table-with-a-highlighted-plan",
        title: "Pattern: Pricing Table with a highlighted plan",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pricing-table-with-a-highlighted-plan.png",
    },
    {
        name: "pattern-colorful-pricing-table",
        title: "Pattern: Colorful Pricing Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-colorful-pricing-table.png",
    },
    {
        name: "pattern-pricing-table-packages",
        title: "Pattern: Pricing Table (Packages)",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pricing-table-packages.png",
    },
    {
        name: "pattern-single-plan-pricing-table",
        title: "Pattern: Single Plan Pricing Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-single-plan-pricing-table.png",
    },
    {
        name: "pattern-pricing-table-with-highlighted-columns",
        title: "Pattern: Pricing Table With Highlighted Columns",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pricing-table-with-highlighted-columns.png",
    },
    {
        name: "pattern-pricing-table-highlighting-discounts",
        title: "Pattern: Pricing Table Highlighting Discounts",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-pricing-table-highlighting-discounts.png",
    },
    {
        name: "pattern-product-box-with-features-description-and-image",
        title: "Pattern: Product Box with features, description, and image",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-product-box-with-features-description-and-image.png",
    },
    {
        name: "pattern-single-product-box-with-features",
        title: "Pattern: Single Product Box with features",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-single-product-box-with-features.png",
    },
    {
        name: "pattern-minimal-product-box",
        title: "Pattern: Minimal Product Box",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-minimal-product-box.png",
    },
    {
        name: "pattern-products-comparison-side-by-side",
        title: "Pattern: Products Comparison Side by Side",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-products-comparison-side-by-side.png",
    },
    {
        name: "pattern-product-lists-comparison-table",
        title: "Pattern: Product Lists Comparison Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-product-lists-comparison-table.png",
    },
    {
        name: "pattern-product-comparison-boxes",
        title: "Pattern: Product Comparison Boxes",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-product-comparison-boxes.png",
    },
    {
        name: "pattern-features-comparison-table",
        title: "Pattern: Features Comparison Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-features-comparison-table.png",
    },
    {
        name: "pattern-brand-size-color-guide",
        title: "Pattern: Brand Size &amp; Color Guide",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-brand-size-color-guide.png",
    },
    {
        name: "pattern-horizontal-pricing-table",
        title: "Pattern: Horizontal Pricing Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-horizontal-pricing-table.png",
    },
    {
        name: "pattern-group-points-table",
        title: "Pattern: Group Points Table",
        upsellText: "",
        image: "/includes/Patterns/images/pattern-group-points-table.png",
    },
];
